export const FONT_LOADERS: Record<string, Record<string, () => Promise<unknown>>> = {
  'source-sans-3': {
    '400': () => import('@fontsource/source-sans-3/400.css'),
    '500': () => import('@fontsource/source-sans-3/500.css'),
    '600': () => import('@fontsource/source-sans-3/600.css'),
    '700': () => import('@fontsource/source-sans-3/700.css'),
    '900': () => import('@fontsource/source-sans-3/900.css'),
    '400i': () => import('@fontsource/source-sans-3/400-italic.css'),
    '600i': () => import('@fontsource/source-sans-3/600-italic.css'),
  },
  'public-sans': {
    '400': () => import('@fontsource/public-sans/400.css'),
    '500': () => import('@fontsource/public-sans/500.css'),
    '600': () => import('@fontsource/public-sans/600.css'),
    '700': () => import('@fontsource/public-sans/700.css'),
    '800': () => import('@fontsource/public-sans/800.css'),
    '400i': () => import('@fontsource/public-sans/400-italic.css'),
    '600i': () => import('@fontsource/public-sans/600-italic.css'),
  },
  'ibm-plex-sans': {
    '400': () => import('@fontsource/ibm-plex-sans/400.css'),
    '500': () => import('@fontsource/ibm-plex-sans/500.css'),
    '600': () => import('@fontsource/ibm-plex-sans/600.css'),
    '700': () => import('@fontsource/ibm-plex-sans/700.css'),
    '400i': () => import('@fontsource/ibm-plex-sans/400-italic.css'),
    '600i': () => import('@fontsource/ibm-plex-sans/600-italic.css'),
  },
  'fira-sans': {
    '400': () => import('@fontsource/fira-sans/400.css'),
    '500': () => import('@fontsource/fira-sans/500.css'),
    '600': () => import('@fontsource/fira-sans/600.css'),
    '700': () => import('@fontsource/fira-sans/700.css'),
    '800': () => import('@fontsource/fira-sans/800.css'),
    '400i': () => import('@fontsource/fira-sans/400-italic.css'),
    '600i': () => import('@fontsource/fira-sans/600-italic.css'),
  },
  'libre-franklin': {
    '400': () => import('@fontsource/libre-franklin/400.css'),
    '500': () => import('@fontsource/libre-franklin/500.css'),
    '600': () => import('@fontsource/libre-franklin/600.css'),
    '700': () => import('@fontsource/libre-franklin/700.css'),
    '800': () => import('@fontsource/libre-franklin/800.css'),
    '400i': () => import('@fontsource/libre-franklin/400-italic.css'),
    '600i': () => import('@fontsource/libre-franklin/600-italic.css'),
  },
  'work-sans': {
    '400': () => import('@fontsource/work-sans/400.css'),
    '500': () => import('@fontsource/work-sans/500.css'),
    '600': () => import('@fontsource/work-sans/600.css'),
    '700': () => import('@fontsource/work-sans/700.css'),
    '800': () => import('@fontsource/work-sans/800.css'),
    '400i': () => import('@fontsource/work-sans/400-italic.css'),
    '600i': () => import('@fontsource/work-sans/600-italic.css'),
  },
  'archivo': {
    '400': () => import('@fontsource/archivo/400.css'),
    '500': () => import('@fontsource/archivo/500.css'),
    '600': () => import('@fontsource/archivo/600.css'),
    '700': () => import('@fontsource/archivo/700.css'),
    '800': () => import('@fontsource/archivo/800.css'),
    '900': () => import('@fontsource/archivo/900.css'),
    '400i': () => import('@fontsource/archivo/400-italic.css'),
    '600i': () => import('@fontsource/archivo/600-italic.css'),
  },
  'barlow': {
    '400': () => import('@fontsource/barlow/400.css'),
    '500': () => import('@fontsource/barlow/500.css'),
    '600': () => import('@fontsource/barlow/600.css'),
    '700': () => import('@fontsource/barlow/700.css'),
    '800': () => import('@fontsource/barlow/800.css'),
    '400i': () => import('@fontsource/barlow/400-italic.css'),
    '600i': () => import('@fontsource/barlow/600-italic.css'),
  },
  'barlow-condensed': {
    '500': () => import('@fontsource/barlow-condensed/500.css'),
    '600': () => import('@fontsource/barlow-condensed/600.css'),
    '700': () => import('@fontsource/barlow-condensed/700.css'),
    '800': () => import('@fontsource/barlow-condensed/800.css'),
    '600i': () => import('@fontsource/barlow-condensed/600-italic.css'),
  },
  'archivo-narrow': {
    '400': () => import('@fontsource/archivo-narrow/400.css'),
    '500': () => import('@fontsource/archivo-narrow/500.css'),
    '600': () => import('@fontsource/archivo-narrow/600.css'),
    '700': () => import('@fontsource/archivo-narrow/700.css'),
    '400i': () => import('@fontsource/archivo-narrow/400-italic.css'),
  },
  'source-serif-4': {
    '400': () => import('@fontsource/source-serif-4/400.css'),
    '500': () => import('@fontsource/source-serif-4/500.css'),
    '600': () => import('@fontsource/source-serif-4/600.css'),
    '700': () => import('@fontsource/source-serif-4/700.css'),
    '800': () => import('@fontsource/source-serif-4/800.css'),
    '400i': () => import('@fontsource/source-serif-4/400-italic.css'),
    '600i': () => import('@fontsource/source-serif-4/600-italic.css'),
  },
  'ibm-plex-serif': {
    '400': () => import('@fontsource/ibm-plex-serif/400.css'),
    '500': () => import('@fontsource/ibm-plex-serif/500.css'),
    '600': () => import('@fontsource/ibm-plex-serif/600.css'),
    '700': () => import('@fontsource/ibm-plex-serif/700.css'),
    '400i': () => import('@fontsource/ibm-plex-serif/400-italic.css'),
    '600i': () => import('@fontsource/ibm-plex-serif/600-italic.css'),
  },
  'charis-sil': {
    '400': () => import('@fontsource/charis-sil/400.css'),
    '700': () => import('@fontsource/charis-sil/700.css'),
    '400i': () => import('@fontsource/charis-sil/400-italic.css'),
    '700i': () => import('@fontsource/charis-sil/700-italic.css'),
  },
  'eb-garamond': {
    '400': () => import('@fontsource/eb-garamond/400.css'),
    '500': () => import('@fontsource/eb-garamond/500.css'),
    '600': () => import('@fontsource/eb-garamond/600.css'),
    '700': () => import('@fontsource/eb-garamond/700.css'),
    '800': () => import('@fontsource/eb-garamond/800.css'),
    '400i': () => import('@fontsource/eb-garamond/400-italic.css'),
    '600i': () => import('@fontsource/eb-garamond/600-italic.css'),
  },
  'ibm-plex-mono': {
    '400': () => import('@fontsource/ibm-plex-mono/400.css'),
    '500': () => import('@fontsource/ibm-plex-mono/500.css'),
    '600': () => import('@fontsource/ibm-plex-mono/600.css'),
    '700': () => import('@fontsource/ibm-plex-mono/700.css'),
    '400i': () => import('@fontsource/ibm-plex-mono/400-italic.css'),
  },
}
